services:
  db:
    image: postgres:18-alpine3.22
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=app-data
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  admin-page:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db