# Đổi cổng mặc định
port 6380

# Giới hạn bộ nhớ tối đa là 128MB
maxmemory 128mb
maxmemory-policy allkeys-lru

# Tắt chế độ bảo vệ để có thể kết nối từ bên ngoài dễ dàng trong bài tập
protected-mode no